# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

# Qrcode generator module

gem 'rqrcode'

gem 'prawn'

gem 'prawn-qrcode'
